#!/bin/bash


# copy procedure
mkdir /tmp/backup
rsync -avAXh $HOME/grepo --exclude 'others' /tmp/backup/dotfiles-`date +%y%m%d_%H%M`

# define the name of a newly created backup
file=$(ls /tmp/backup)

# make an atomic 7z archive and remove the backup
apack -qq /tmp/backup/$file.tmp.7z /tmp/backup/$file

mv /tmp/backup/$file.tmp.7z $HOME/filez/backup/$file.7z

rm -rf /tmp/backup
