#!/bin/bash

# removing build dependencies installed with apt-get build-dep
deprem() {
    sudo aptitude markauto $(apt-cache showsrc $1 | grep Build-Depends |
    perl -p -e 's/(?:[\[(].+?[\])]|Build-Depends:|,|\|)//g')
}

deprem
