#!/bin/bash

# convert markdown to html with pandoc
md2html() {
    local IFS=+
    local format=(
        markdown_github
        footnotes
        fenced_code_attributes
        pandoc_title_block
        shortcut_reference_links
    )
    local pandoc_options=(
        -f "${format[*]}"
        -s                                  # produce output with header and footer
        -S                                  # produce typographically correct output
        --toc                               # table of contents
        -c $HOME/.pandoc/css/pandoc.css     # path to custom css styles
    )
    pandoc "${pandoc_options[@]}" "$@"
}

md2html
