#!/usr/bin/env bash
shopt -s globstar

##
##  notifi
##      :: daemon integrating $HOME executables into one folder
##  v1kn
##  https://github.com/v1kn
##  2016/12/06
##

dirs="$HOME/.gem/ruby/2.3.0/bin $HOME/.local/pyvenv/bin $HOME/grepo/bin"

while inotifywait -e create -e delete -e modify -e attrib -e move $dirs; do
    find $HOME/.local/bin \
        -type l \
        -delete
    find $dirs \
        -follow \
        -mindepth 1 \
        -maxdepth 1 \
        -type f \
        -executable \
        -exec ln -s {} $HOME/.local/bin \;
    #find $dirs -follow -mindepth 1 -maxdepth 1 -type f -executable -exec ln -s ${PWD}/{} $HOME/.local/bin \;
done
