#!/bin/bash
shopt -s globstar

dirs="$HOME/.cargo/bin $HOME/.gem/*/bin $HOME/.local/pyvenv/bin $HOME/git-repos/bin"

while inotifywait -e create -e delete $dirs; do
    find $HOME/.local/bin -type l -delete
    # arch
    find $dirs -type f -executable -exec ln -s {} $HOME/bin \;
    # ubuntu
    #find $dirs -type f -executable -exec ln -s ${PWD}/{} $HOME/bin \;
done
