#!/usr/bin/env bash
set -euo pipefail

for arg; do
    case "$arg" in
        -?*) ;;
        *)
            realarg="$(realpath "$arg")"
            case "$realarg" in
                /|/usr|/var|/etc|/home|/home/vlkn|/bin|/lib|/lib64|/boot|/opt|/media|/root)

                    echo "refusing to remove $realarg" 1>&2
                    exit 100
                    ;;
            esac
            ;;
    esac
done

exec /bin/rm --one-file-system --preserve-root "$@"
