#!/usr/bin/env bash

##
##  TODO
##

webhome="/media/wde2/websites"
linklist="$HOME"/wget.lnk
downloadedlist=$(find "$webhome"/html/ \
    -type f \
    -daystart \
    -mtime 0 \
    -printf '%P\n')
pdflist=$(find "$webhome"/pdf/ \
    -type f \
    -daystart \
    -mtime 0 \
    -printf '%P\n')

while read link; do
    wget -a "$HOME"/wget.log "$link"
    htmlfile="$HOME"/$(tail "$HOME"/wget.log \
        | grep "Converting" \
        | cut -d\  -f2 \
        | sed 's/html.../html/')
    cp "$htmlfile" "$webhome"/html/
done <<< $(echo "$linklist")

while read downloadedfile; do
    newname=$(grep "<title>" "$downloadedfile" \
        | cut -d\> -f2 \
        | cut -d\< -f1)
    mv "$webhome"/html/$downloadedfile \
        "$webhome"/html/"$newname".html
    wkhtmltopdf "$newname".html "$webhome"/pdf/"$newname".pdf
done <<< $(echo "$downloadedlist")

##  removing spaces and uppercase from html and pdf
for i in "$downloadedlist"; do
    sed 's/ /-/g' "$i" | tr '[:upper:]' '[:lower:]'
done

for ii in "$pdflist"; do
    sed 's/ /-/g' "$ii" | tr '[:upper:]' '[:lower:]'
done
