#!/bin/bash

##
## vdl - script for fetching new vids from yt
## htps://github.com/v1kn
## 20150421 - init
## 20161213 - major rewrite (collapsing 2 loops into 1)
##

# script files parent directory
# `readlink -f` will resolve symlinks, but is most likely GNU specific
src="$( cd "$( dirname $(readlink -f "${BASH_SOURCE[0]}") )" && pwd)"

__main() {
    for i in "$src"/vdl-users "$src"/vdl-channels; do
        while read item; do
            # grep video IDs, put them in a temp file
            [[ "$i" = "$src"/vdl-users ]] && uorc="user" || uorc="channel"
            lynx --source "https://www.youtube.com/"$uorc"/"$item"/videos" \
                | grep data-context-item-id \
                | cut -d\= -d\" -f2 \
                | sed -n '1,20p' \
                | cat > "$src"/ytfile-"$item"-temp

            # define variables and diff them
            oldfile="$src"/ytfile-"$item"
            newfile="$src"/ytfile-"$item"-temp
            newvidlist=$(diff "$newfile" "$oldfile" \
                | grep "<" \
                | cut -d\< -f2 \
                | sed -e 's/^[[:space:]]*//')

            if [[ -n "$newvidlist" ]]; then
                # download new videos
                while read newvid; do
                    echo -e "\nfound new videos from "$item"\ndownloading"
                    youtube-dl -- "https://www.youtube.com/watch?v="$newvid""
                done <<< "$(echo "$newvidlist")"
                # merge new vid IDs into user ytfile atomically
                echo "$newvidlist" \
                    | cat - "$src"/ytfile-"$item" \
                    > "$src"/ytfile-"$item"-merge \
                    && mv "$src"/ytfile-"$item"-merge "$src"/ytfile-"$item"
                rm "$newfile"
            else
                echo -e "\nno new videos from "$item""
                [[ -f "$newfile" ]] && rm "$newfile"
            fi
        done <<< "$(< "$i")"
    done
}

# printf '%13s%b\n' | tr " " "="
echo -e "\n============================\n$(date)"
__main
notify-send -t 10000 "Check for new YT vids"
